= JD Edwards™ Connector Release Notes
:keywords: JDE, JDEdwards, EnterpriseOne, Oracle, JD Edwards

The ModusBox’s _JD Edwards Connector_ aims to provide integration from and to Oracle’s _JD Edwards™ EnterpriseOne™_.
It leverages the power of Oracle's Java Dynamic Connector and XML List to provide interoperability with Oracle’s _JD Edwards EnterpriseOne™_ and external systems.

link:http://modusintegration.github.io/mule-connector-jde/1.3.0/functional/user-manual.html[JDE Connector user guide].

== JD Edwards™ Connector 1.3.0 - May 30, 2017

=== Version 1.3.0 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0 and higher
|Oracle's JDE Enterprise Server|This connector works with Oracles's JDE Edwards Enterprise One Tool Release Tool Release 8.98 Update 4 onwards
|===

=== Migrating from Older Versions

The attribute **imageFolderCache** in JDE Configuration has been removed. In the XML configuration, look for the `<jde:config>` tag and delete parameter `imageFolderCache`

From this version, the JDE Connector will save the temporary specs in System Temporary Directory (*java.io.tmpdir*) under the folder with the same name of the environment.

Ex. **C:\Users\username\AppData\Local\Temp\JPS920**

=== Features

. Redirecting JDE Logger to Mule Logger. It allows seeing JDE activity in both Console and JDE file defined in jdelog.properties.
. DNS resolver has been added to allow JDE Connectors works on CloudHub with VPC.
. The connector now has the possibility to deploy more than one set of INI files for each environment.
. Spec Cache Folder in the configuration now is optional. By default, this folder will be the system temporary directory.
. From now on, the operation will throw its own Exception object instead of throwing always RuntimeException object. The new exceptions are BSFNTransactionException, CallBSFNException, JobStatusException, SubmitUBEException, EventException. These exceptions are extended of JDEConnectorException.
. JDE Connector testing has been improved to show the real error validating the connections.
. The Call Business Function operation now will return a XML in the parameter_BSFNDetailErrors instead of a String. This XML will be a representation of CallObjectErrorList object.


=== Version 1.3.0 Fixed in this Release

JDE 9.2 do not accept a null UTIME as input nor output. There was an error in the log: Not attempting to create JDECALENDAR object
We are adding a non-null value as input in spite of the parameter is output



=== Version 1.3.0 Known Issues

None

== JD Edwards™ Connector 1.2.0 - March 15, 2017

=== Version 1.2.0 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0 and higher
|Oracle's JDE Enterprise Server|This connector works with Oracles's JDE Edwards Enterprise One Tool Release Tool Release 8.98 Update 4 onwards
|===

=== Features

. The BSFN Call Operation now displays all the JDE's Functions. The user can now select one function from the list or also can type the name.
. It has been added a UBE test and Call BSFN in Test Connection to validate Enterprise Server configuration.

=== Version 1.2.0 Fixed in this Release

Error when the connector call a BSFN after a commit or rollback a transaction.

=== Version 1.2.0 Known Issues

None

== JD Edwards™ Connector 1.1.1 - July 5, 2016

=== Version 1.1.1 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0 and higher
|Oracle's JDE Enterprise Server|This connector works with Oracles's JDE Edwards Enterprise One Tool Release Tool Release 8.98 Update 4 onwards
|===

=== Features

None

=== Version 1.1.1 Fixed in this Release

. Fixed call object concurrency in multi-threaded applications. There was an exception when the connector trying to open more than one session at the same time. Now, the connector has a lock before opening the session.

. Support for more than one Transaction Session in multi-threaded applications has now been improved

=== Version 1.1.1 Known Issues

None

== JD Edwards™ Connector 1.1.0 - June 15, 2016

=== Version 1.1.0 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0 and higher
|Oracle's JDE Enterprise Server|This connector works with Oracles's JDE Edwards Enterprise One Tool Release Tool Release 8.98 Update 4 onwards
|===

=== Migrating from Older Versions

The attribute **enviroment** in JDE Configuration has been renamed to **environment**. In the XML configuration, look for the `<jde:config>` tag and change parameter `enviroment` to `environment`

This version adds optional parameters to existing operation:

- BSFN Call
- Submit Batch Process

=== Features

. New parameters allow the invocation of BSFNs with the benefit of gaining more control over errors:
( _BSFNThrowExceptionWithErrorsYN, _BSFNReturnCode, _BSFNNumberOfErrors, _BSFNDetailErrors)
. Capability to include Data Selection to filter the records to process when submitting UBEs.
. Poll Events - It allow get out outbound events that it come from an application that uses a *Master Business Function* to generate transactions with Interoperability activated.
. Poll EDI Events - It allow to capture outbound transactions that it generated from EDI Module applications.
. BSFN Transactions - It allow to invoke one or more BSFN in the same database transaction.

=== Version 1.1.0 Fixed in this Release

Development tab from Configuration has been removed.

Mavenized applications can’t reference the JDE bundle (refer to the User Manual).


=== Version 1.1.0 Known Issues

None

== JD Edwards™ Connector 1.0.1 - September, 2015

=== Version 1.0.1 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0 and higher
|Oracle's JDE Enterprise Server|This connector works with Oracles's JDE Edwards Enterprise One Tool Release Tool Release 8.98 Update 4 onwards
|===

=== Features

. Log into _JD Edwards EnterpriseOne™_. Authentication over _EnterpriseOne Security Server_.
. Discover BSFNs by name.
. Resolve BSFN metadata (signature and parameters) at runtime.
. Cache BSFN & UBE definitions locally in xml format.
. Invoke a BSFN by name.
. Submit UBEs.
. Check for UBEs status

=== Version 1.0.1 Fixed in this Release

Due to a limitation in the testing framework a Development tab is being displayed.

=== Version 1.0.1 Known Issues

Due to a limitation in the testing framework a Development tab is being displayed.

Mavenized applications can’t reference the JDE bundle (refer to the User Manual).

=== Support Resources
* Learn how to link:https://docs.mulesoft.com/mule-user-guide/v/3.7/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s MuleForge link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].
