= Examples
:keywords: b2b, portal, partner, manager, environments

This page identifies examples of  xref:index.adoc[PortX] in use.

For conceptual information, see xref:key-concepts.adoc[Key Concepts].

For information about the procedures you would use to implement a given example, see xref:partner-configuration.adoc[Configure Trading Partners] and xref:transaction-monitoring.adoc[Transaction Monitoring].


== End-to-End Use Case

=== In PortX

* Enter home organization settings
* Enter external trading partner settings

=== In ESB

. Create your flow.
. Configure the PortX Connector.
. Configure PortX-enabled connectors to use the PortX Connector.
. Use standard connectors and processors to complete the processing and integration of the message into downstream systems as required.

=== Back in PortX

Go to the B2B Transmissions area of PortX to view tracked events and messages.

// include::_sources/content-based-routing-example.adoc[]


// Promotion Scenarios


include::{partialsdir}/promotion-scenarios.adoc[leveloffset=+1]

// removed image PromoteIDsOffCertsOn kris 7/1/2017


include::{partialsdir}/tracking-scenarios.adoc[leveloffset=+1]
