= Welcome to PortX(TM)!

PortX powers integration with products designed for use with an Enterprise Service Bus (ESB). 

|===
| Attributes
 
|
ifdef::intermediate[:intermediate:]
ifndef::intermediate[:intermediate!:]
 
|
ifdef::advanced[:advanced:]
ifndef::advanced[:advanced!:]
 
|===
 
 
ifdef::advanced[]
This is only visible if we
set the advanced attribute.
endif::advanced[]
 
ifdef::intermediate,advanced[]
Here is some content for the
intermediate or advanced readers,
which is visible if the attributes
intermediate or advanced are set.
endif::intermediate,advanced[]
 
ifdef::intermediate+advanced[]
Here is some content for the
intermediate and advanced readers,
which is visible if the attributes
intermediate AND advanced are set.
endif::intermediate+advanced[]

== General ESB

For information about products built to power integration on most Enterprise Service Bus platforms, see these libraries:

* xref:Other ESB@partner-manager::index.adoc[Partner Manager]
* xref:Other ESB@partner-manager-connector:ROOT:partner-manager-connector.adoc[Partner Manager Connector]

== Specific ESB

For information about products built to power integration on specific platforms, see these libraries.

=== Mulesoft

* xref:Mulesoft ESB@partner-manager:ROOT:index.adoc[Partner Manager (Mulesoft)]
* xref:Mule ESB@partner-manager-connector:ROOT:partner-manager-connector.adoc[Partner Manager Connector (Mulesoft)]

////
* xref:as2-connector:ROOT:as2-connector.adoc[AS2 Connector]
* xref:ftps-connector:ROOT:ftps-connector.adoc[FTPS Connector]
////
