= Company Information

== Add a New Partner or Application

. On the Partners and Applications Page, click *Add Partner* or *Add Application*.

Either the
Partner or Application information page appears.

=== Enter Contact Information

////
. The name of the partner you selected on the Trading Partners Page (or added on this page, as a new partner) appears in the *Company Name* box. If appropriate, you can change it.
////
[start=2]
. In the *Contacts* section of the *Company information* page, enter the following:

** *Partner Name*
** *Contact type* +
(In the dropdown listbox, select *Technical*, *Business*, or *Both*.)
. After you enter a contact type, you can enter the following contact-specific information. All fields are xref:glossary#s[standard PortX field format].

** *First Name*
** *Last Name*
** *Title*
** *E-mail*
** *Office Phone*
** *Mobile Phone*
** *Fax*
** *Country*
** *Address Line 1*
** *Address Line 2*
** *City*
** *State*
** *Postal Code*


. Click *Save* to save the values you entered.

Note:: You may click *undo* at any time in the upper right hand corner to reverse an entry. 
