= modusbox-docs

This repo is used for the modusbox documentation. This repo is automated so any changes to the dev/stg/prod
branches is automaticly built and pushed to there respective environment

dev: `http://modusbox-docs.s3-website-us-west-2.amazonaws.com/portx/latest/index.html`

stg: `http://staging.docs.portx.io/portx/latest/index.html`

prod: `https://docs.portx.io/portx/latest/index.html`



There also is a test environment which can but used to test any builds or branches. Once you have aws configured, and
you have a build you want to push to the test environment. You can simply run `make push-test` and it will take whatever
build you have in your local build folder.

test: `https://docs.portx.io/portx/latest/index.html`

### port-ui
A requirement for this repo is https://github.com/modusintegration/port-ui[port-ui], it is used to create customized ui bundles.
For the automated release via github actions,
the master branch of port-ui is used for building the dev docs environment,
the staging-links branch of port-ui is used for building the stg docs environment,
and the prod-links of branch port-ui is used for building the prod docs environment.

== Getting Started

Once you get gulp installed see bellow you can simply run `make bundle` if successful you will a new file generated at `build/ui-bundle.zip`
You can then use this bundle by coping it over to the modusbox-docs repo.
