= modusbox-docs

This repo is used for the modusbox documentation. This repo is automated so any changes to the dev/stg/prod
branches is automaticly built and pushed to there respective environment

dev: `http://modusbox-docs.s3-website-us-west-2.amazonaws.com/portx/latest/index.html`

stg: `http://staging.docs.portx.io/portx/latest/index.html`

prod: `https://docs.portx.io/portx/latest/index.html`



There also is a test environment which can but used to test any builds or branches. Once you have aws configured, and
you have a build you want to push to the test environment. You can simply run `make push-test` and it will take whatever
build you have in your local build folder.

test: `https://docs.portx.io/portx/latest/index.html`

### port-ui
A requirement for this repo is https://github.com/modusintegration/port-ui[port-ui], it is used to create customized
ui bundles.

### AWS config
If you want to upload to the test environment you will need to configure an aws profile
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html[aws-docs]. You will need to make sure your
key is for the `portx-prod` account.


== Getting Started

Once you have made an appropriate bundle from port-ui you can simply move it into `/build-resources`. Then run
`make playbook` which will generate the site from the defined playbooks


    site-nn-head-esb-3.yml,
    site-nn-head-mule-3.yml,
    site-nn-head-camel-3.yml

and automaticly put the site into your `/build` directory. Once the site is built you can run `make local` which will
open up your local site you just built.

