= Examples
:keywords: b2b, portal, partner, manager, environments

This page identifies examples of  xref:anypoint-partner-manager[PortX] in use.

For conceptual information, see xref:key-concepts[Key Concepts].

For information about the procedures you would use to implement a given example, see xref:partner-configuration[Configure Trading Parners] and xref:transaction-monitoring[Transaction Monitoring].


== End-to-End Use Case

In this example, a user performs a series of configuration tasks in PortX and Anypoint Studio, resulting in the ability to view events and track transmissions.

=== In PortX

* Enter home organization settings
* Enter external trading partner settings

=== In ESB

. Create your flow.
. Configure the Partner Manager Connector.
. Configure Partner Manager-enabled connectors to use the Partner Manager Connector.
. Use standard connectors and processors to complete the processing and integration of the message into downstream systems as required.

=== Back in PortX

Go to the B2B Transmissions area of PortX to view tracked events and messages.

// include::_sources/content-based-routing-example.adoc[]


// Promotion Scenarios

include::{partialsdir}/promotion-scenarios.adoc[leveloffset=+1]


// Tracking Scenarios

include::{partialsdir}/tracking-scenarios.adoc[leveloffset=+1]
