== Documents View
:icons: font
The Documents View presents data on documents that are sent through xref:transaction-monitoring.adoc[Transaction Monitor]

=== Content
Each row has 6 columns:

. *From*: Who the document was sent from

. *To*: Who the document was sent to

. *Date*: Date and time at which the document was sent

. *Standard*: The standard used to send the document

. *Message Type*: The type of message that was sent

. *Label*: Information describing the document

=== Document Detail Pane (Right)
This pane is hidden when no document is selected. It contains:

* Document ID icon:plus-square-o[role="blue"]
* Document Definiton ID icon:plus-square-o[role="blue"]
* Standard
* Version
* Message Type
* From
* To
* Date
* Duplicate Quiry
* Message Payload icon:share[role="blue"]
* Partnership ID icon:plus-square-o[role="blue"]

==== Action Icons
* The copy icon icon:plus-square-o[role="blue"] allows you to copy informaiton to your clipboard
* The share icon icon:share[role="blue"] opens a detail pane that shows the complete message payload.
This pane allows you to:
** Copy Payload URL
** Download 
** Copy content to clipboard

==== Buttons
* A *Transaction* icon:exchange[] button will appear when a document is selected
** This will take you to the <<Transaction view>> and highlight this specific document

=== Filters
You can filter documents based on:

Date::
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range
** *From*: Select a date from the calendar; only documents that occurred after that date will appear.
** *To*: Select a date from calendar; only documents that occurred before that date will appear

View::
* Both
* Partners
* Applications

Relationship:: Select the partner or application that is associated with the document
Message Type:: Enter the message type found in the <<Document Detail Pane (Right)>>
Property Name:: Select the document property name from the dropdown list
Property Value:: Enter the document property value found in the <<Document Detail Pane (Right)>>
Standard:: Select the document standard protocol from the dropdown list
Document ID:: Enter the document ID found in the <<Document Detail Pane (Right)>>

==== To Show all Documents
Click [blue]#*Reset filters*# in the top right.
