== Documents View
The Documents View presents data on documents that are sent through xref:transaction-monitoring.adoc[Transaction Monitor]

=== Content Area
Each row has 6 columns:

. *From*: Who the document was sent _from_

. *To*: Who the document was sent _to_

. *Date*: _Date and time_ at which the document was sent

. *Standard*: The _standard protocol_ used to send the document

. *Message Type*: The type of message that was sent

. *Label*: Information describing the document

=== Detail Pane (Right)
Hidden when no document is selected, and contains:

* Document ID icon:fa fa-plus-square-o[role="blue"]
* Document Definiton ID icon:fa fa-plus-square-o[role="blue"]
* Standard
* Version
* Message Type
* From
* To
* Date
* Duplicate Quiry
* Message Payload icon:fa fa-share[role="blue"]
* Partnership ID icon:fa fa-plus-square-o[role="blue"]

==== Action Icons
* The _copy_ icon icon:fa fa-plus-square-o[role="blue"] allows you to copy informaiton to your clipboard
* The _share_ icon icon:fa fa-share[role="blue"] opens a detail pane that shows the complete message payload.
This pane allows you to:
** Copy Payload URL
** Download 
** Copy content to clipboard

==== Buttons
* A *Transaction* icon:fa fa-exchange[] button will appear when a document is selected
** This will take you to the *Transaction* view and highlight this specific document

=== Filters

Date::
In the <<Timeframe Dropdown List>> you can filter by:
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range
From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear

View::
In the <<View Dropdown List>> filter by:
* Both
* Partners
* Applications
////
Direction:: Inbound or Outbound
////
Partner:: Filter by the Partner that is associated with the document
Message Type:: Filter for message type field containing string
Property Name:: Filter for document having property name
Property Value:: Filter for document having property value containing string
Standard:: Filter by the standard
Document ID:: Filter by document id

==== To show all documents
Click *Clear filters*.

=== Top Bar
* A *Transaction* button will appear when a document is selected
** This will take you to the *Transaction* view and highlight this specific document
