== Tracking Errors
If you encounter errors in Transaction Monitor, you can review, assess, and replay these errors by tracking them in Ihub. Start by tracking individual errors in Transactions View, and continue by tracking multiple errors in Errors View.

See xref:central-pane-elements.adoc#errors.view[Errors View] for more information. 

To replay a transaction, see xref:tracking-examples.adoc#replaying-an-incomplete-transaction[Replaying an Incomplete Transaction].

=== Track in the Dashboard

The xref:central-pane-elements.adoc#dashboard[Dashboard] at the top of the xref:transaction-monitoring.adoc[Transaction Monitoring Page] provides a data summary of what has happened in a given timeframe (the default is the current day) including how many errors have been detected during that timeframe.

. Hover over different slices of the Errors Pie Chart to see what types of errors have occurred.
. To see information for a given error type, click one of the slices.
+
The Errors View appears, showing only the error type you selected.
+
This enables you to look for a pattern among these errors that help facilitate a solution. This is useful when transactions are failing. but you can't ascertain the solution by just looking at the transactions themselves.

=== Track in Transaction View
Follow these steps to track errors in Transactions View.

Start::
. Select *Transactions* in the View Dropdown List.
+  
The Transactions View appears.

. In the Timeframe Dropdown List, choose an appropriate timeframe that includes the time of the error event(s).
+ 
Only transactions of that timeframe appear in the Content Area.
. Check the *Only Having Errors* checkbox in the Filter Bar.
+
Only errors appear in the Content Area.
. Locate the error in the Content Area, or <<Track by Relationship>>.
. Click on the error.
+ 
The Transaction Event Rows appear.
. Click on the error event from the Transaction Event Rows.
+
The Error Detail Pane appears.
. Click the blue copy icon next to Source ID.
. Paste the Source ID in the *Transaction ID* Tab in the Filter Bar.
+ 
Only this Transaction appears in the Content Area.

//-
See xref:tracking-examples.adoc#replaying-an-incomplete-transaction[Replaying an Incomplete Transaction] for instructions to replay a transaction.

==== Detail Pane
Use information in the Detail Pane to facilitate a solution to the error.

Error Message::
. Select the error from the transaction the Content Area.
+
The Error Detail Pane appears.
. Click the blue file code icon next to the *Error Message*.
+ 
An error message appears.
. Use values in the Error Message to facilitate a solution to the error.

//-
* To return to the transaction associated with the error, click the *Transaction* button in the detail pane.

See xref:tracking-examples.adoc#replaying-an-incomplete-transaction[Replaying an Incomplete Transaction] for instructions to replay a transaction.

==== Track by Relationship

Start::
. Select *Transactions* in the View Dropdown List.
+
The Transactions View appears.
. Click on the transaction that failed to play in the Content Area.
. Note the _From_ and _To_ variables in the Transaction.
. Select *Errors* in the View Dropdown List.
+
The Errors View appears.
. Click the *Relationship* tab in the Filter Bar.
+
The Relationship Filter Dropdown list appears.
. Enter the _From_ and _To_ variables of the transaction in the dropdown list.
+
Only errors of this relationship appear in the Content Area.

See xref:tracking-examples.adoc#replaying-an-incomplete-transaction[Replaying an Incomplete Transaction] for instructions to replay a transaction.

==== Track by Error ID

. Select *Transactions* in the View Dropdown List.
+ 
The Transactions View appears.
. Click on the transaction that contains the error.
+
The Transaction Event Rows appear.
. Click on the Error Event in the Transaction Event Rows.
+ 
The Error Detail Pane appears.
. In the Detail Pane, click the blue copy icon next to the *Error ID*.
. Select *Errors* in the View Dropdown List.
+
The Errors View appears.
. Paste the Error ID in the *Error ID* tab on the Filter Bar.
+
Only this error appears in the Content Area below.

* Save Error ID's while reviewing transactions, and use them to track specific errors in the Errors View. 

NOTE: You can always use the *Reset Filters* button to get back to the full view.

=== Track in Errors View
Use the Errors View to track and compare multiple errors.
It may be useful to first collect information from the Error Detail Pane by tracking in Transactions View, to assist with tracking errors in Errors View.

Viewing Filter::
Use the Viewing Filter to batch all errors in the Content Area by partner or application, select one of the following buttons in the Filter Bar.

** Both (Default)
** Partners
** Applications

==== Track by Error Code
Use the Error Code to determine where multiple errors of a specific error type are occurring.

Start::
. Select *Errors* in the View Dropdown List.
+
The Errors View appears.
. Enter the error code in the *Error Code* tab.
+ 
Only errors of that code type appear in the Content Area.

==== Track by Error Source
Use the Error Source filter to track errors from the following source types:

* Transaction
* Transmission
* Document

//-
Start::

. Select *Errors* in the View Dropdown List.
+
The Errors View appears.
. Click the *Error Source* tab in the Filter Bar.
+ 
The Error Source Dropdown List appears.
. Click on the *Error Source*.
+
Only errors of this source type appear in the Content Area.

==== Track by Relationship (Your Company B2B)
Use the Relationship filter to track errors between Actors (partners or applications). This filter is useful in that it allows you to track multiple errors that may occur between Your Company and a specific Actor.

. Select *Errors* in the View Dropdown List.
+
The Errors View appears.
. Click the *Relationship* tab in the Filter Bar.
+
The Relationship Dropdown List appears.
. In the dropdown list select Your Company and the Actor.
+
Only errors of this relationship appear in the Content Area below.

* You can view errors associated with other actor relationships by setting new values in the Relationship Filter.

//-
Relationship Filter Settings ::

* Application -> Partner
* Partner -> Partner
* Application -> Application
* Your Company -> Application
* Your Company -> Partner

You can then apply additional filters to <<Track by Error Source>> and <<Track by Error Code>> to further review and track errors. 

NOTE: You can always use the *Reset Filters* button to get back to the full view.

