== Tracking Transactions
Tracking transactions is a primary function of analyzing B2B communications in Ihub.

See also xref:central-pane-elements.adoc#transactions-view[Transactions View] for more information.

=== Track in the Dashboard
The xref:central-pane-elements.adoc#dashboard[Dashboard] at the top of the xref:transaction-monitoring.adoc[Transaction Monitoring Page] provides a data summary of what has happened in a given timeframe (the default setting is current day) including how many transactions have been detected during that timeframe.

Start::
. Hover over different slices of the Transactions Pie Chart to see what types of transactions have occurred.
. To see information for a given transaction type, click one of the slices.
+
The appears, showing only the transaction type you selected.

=== Track in Transactions View
Use Transactions View to quickly filter content and track transactions.

Viewing Filter::

Apply the Viewing filter at any time to batch transactions by Actor Type in the xref:central-pane-elements.adoc#content-area[Content Area]. You may select the following buttons in the xref:central-pane-elements#filter-bar[Filter Bar].

* Both
* Partners
* Applications

==== Track with Transaction ID
Use the *Transaction ID* tab in the Filter Bar to locate a transaction.

. Select *Transactions* in the View Dropdown List
+  
The Transaction View appears.
. Enter the Transaction ID in *Transaction ID* tab in the Filter Bar.
+
Only this transaction appears in the Content Area.
. Click on the transaction.
+ 
The Transaction Detail Pane appears.

==== Detail Pane
The Transaction Detail Pane includes:

* Who the transaction is From
* Who the transaction is To
* Date of the Transaction
* The Transaction ID

//-
View Preceding or Next Transaction::
If the Transaction is part of a stream of Transactions from one Actor Relationship, you can click the following links.
. Click *View Preceding Transaction* in the Detail Pane.
+
Only the current and preceding transaction appear in the Content Area.
. Click *View Next Transaction* in the Detal Pane.
+
Only the current and next transaction appear in the Content Area.

//-
View Original::
If the Transaction is a replay:
. Click *View Original* in the Detail Pane.
+
Only the original and the replayed transaction appear in the Content Area. 

View Replays::
If the transaction is replayed:
. Click *View Replays* in the Detail Pane.
+
Only the replayed transactions, and the original appear in the content area.


==== Track by Relationship (Your Company B2B)
Use the Relationship filter to track trasactions between Actors (partners or applications). This filter is useful in that it allows you to track multiple transactions that occur between Your Company and specific Actors.

Start::
. Select *Transactions* in the View Dropdown List.
+
The Transactions View appears.
. In the Timeframe Dropdown List, choose an appropriate timeframe that includes the time of the transaction event.
+
Only transactions of that timeframe appear in the Content Area.
. Click the *Relationship* tab in the Filter Bar.
. In the Relationship Dropdown List select *Your Company* and the *Actor*.
+
Only transactions of this relationship appear in the Content Area.

Note:: You can view transactions of other actor relationships by setting new values in the Relationship Filter.

Relationship Filter Settings::

* Application → Partner

* Partner → Partner

* Application → Application

* Your Company → Application

* Your Company → Partner

NOTE: You can always use the *Reset Filters* button to get back to the full view.