= Tracking Examples
:keywords: Anypoint b2b Integration Hub concepts

This section identifies examples in which Integration Hub (IHub) is useful to track B2B exchanges. A basic knowledge of Ihub is assumed; see xref:integration-hub.adoc[Integration Hub] for more information.


== Replaying an Incomplete Transaction

On the xref:transaction-monitoring.adoc[Transaction Monitor Page], the xref:central-pane-elements.adoc#transactions-view[Transactions View] includes a table in which each row corresponds to a transaction.  The first column shows transaction completion status, as follows:

Green checkmark:: Indicates a complete transaction.
Red exclamation point (*!*):: Indicates a transaction has one or more errors that prevented completion.

After you identify and fix the cause of the error that prevented the transaction from completing, you can re-run the transaction.

Possible errors include:

* Server down
* Dependency (for example, a map or code element) has changed
* Required data is absent

NOTE: Only replay transactions after resolving the issue or issues that caused the error.

For more information, see xref:central-pane-elements.adoc#transactions-view[Transactions View].

=== To Replay a Transaction

. Click the row corresponding to the transaction you want to replay.
+
NOTE: For a transaction to be replayable, the third (Replay Status) column must be blank or contain a gray partial circle, but must not contain a blue partial circle.
+
A blue *Replay* button appears in the top xref:central-pane-elements.adoc#dashboard[Dashboard].
+
. Click the blue *Replay* button.
+
The button becomes unclickable, and a message that the transaction is being replayed appears in its place.
+
Once the transaction has been replayed, the blue replay circle appears in the Replay Status Column of the transaction that you replayed.
+
. To see if the replayed transaction succeeded or failed, click the replayed transaction.
+
. In the Transaction Detail Pane, a link to *view replays* appears.
+
This automatically filters the content area in xref:transactions-view.adoc[Transactions View] by *Transaction ID*, so that only transactions that are replays of the original transaction appear.
+
If the replayed transaction fails again, repeat this process until the replay completes.
+
You can always view a list of all of your transactions that have been replayed from a given original transaction, by clicking the *view replays* link in the Transaction Detail Pane for any transaction in which the blue replay circle appears in the Replay Status Column.
+
Once the replay succeeds, a green check appears next to the replayed transaction.

NOTE: If you need to continue replaying the transaction, you can do so with the same replay button as before, but you will be alerted with a warning before you can continue. This is to prevent unnecessary replays from happening.

== Tracking Errors
If you encounter errors in Transaction Monitor, you can review and assess these errors.

=== View Error Information in the Dashboard

The xref:central-pane-elements.adoc#dashboard[Dashboard] at the top of the xref:transaction-monitoring.adoc[Transaction Monitoring Page] provides a summary of what has happened in a given timeframe (the default is the current day) including how many errors have been detected during that timeframe.


. Hover over different slices of the Errors Pie Chart to see what types of errors have occurred.
. To see information for a given error type, click one of the slices.
+
The xref:errors-view.adoc[Errors View] appears, showing only the error type you selected.
+
This enables you to look for a pattern among these errors that will facilitate a solution to the errors. This is useful when transactions are failing. but you can't ascertain the solution by just looking at the transactions themselves.
+ 
* The *Transaction* button in the Error Detail Pane at the top right enables you to view the transactions with which these errors are associated.

=== View Error information from the Detail Pane
. Select the xref:errors-viw.adoc[Errors View] from the Central Pane
+ 
The xref:errors-view.adoc#error-detail-pane[Error Detail Pane] opens on the right.
. Click the blue file code icon next to the Error Message.
+ 
An error message appears.

You may copy and then filter values found in the Error Message such as the Error Code.

To locate the transaction associated with the error, copy the Source ID from the Error Message and pasting it into the Transaction ID filter in the Transaction View, or click the *Transaction* button in the detail pane.

==== Filtering by Relationshp (Your Company B2B)
Using the Relationship filter allows you to track errors between specific partners and applications. This filter is useful in that it allows you to assess the source of multiple errors that may occur between specific trading partners.

. Select the Errors View in the xref:central-pane-elements#view-dropdown-list[View Dropdown List].
. Click the *Relationship* tab in the Filter Bar.
. In the dropdown list select _Your Company_ on the left and a partner or application on the right.
+
Only errors of this relationship appear in the Content Area below.

You can view errors associated with other partner relationships by  setting new values in the Relationship Filter.

Relationship Filter Settings ::

* Application -> Partner
* Partner -> Partner
* Application -> Application
* Your Company -> Application
* Your Company -> Partner

You can then apply additional filters such as *Error Source*, to further track where an error occurs. 

==== Filtering by Error ID

. Select the *Transactions View* in the Central Pane
. Click on the Transaction that contains an error.
. In the Detail Pane, click the blue copy icon next to the *Error ID*.
. Select the *Errors View* in the Central Pane
. In the Filter Bar, paste your copy in the *Error ID* tab.
+
The Error appears in the Content Area below.

You can save Error ID's while reviewing Transactions, and use them to filter to a specific error in the Errors View. 

==== Filtering by Error Code
You can filter by Error Code to determine where multiple errors of a specific type are occuring. 

. Select the Errors View in the Central Pane
. Enter the name or number (0 to 6) of the Error code you are filtering in the Error code search option on the Filter Bar. 
+ Only errors with that code appear in the Content Area below.

==== Filtering by Error Source
You can filter Errors from the following sources:

* Transaction
* Transmission
* Document

. Select the *Errors View* in the Central Pane
. Select the source under the *Error Source* tab in the Filter Bar.
+ 
Only errors of that source type appear in the Content Area below.

Combigne the *Error Source* Filter with parameters set in the xref:central-pane-elements.adoc#timeframe-dropdown-list[Timeframe Dropdown List] to track errors of this source over time.

== Tracking Transmissions 
Transaction monitor allows you to track transmissions. Tracking a transmission is useful in that it allows you analyze the flow in which documents are traveling through Ihub.  


=== Filtering by Transport
A transport is the protocol in which a document is recieved and/or sent. The type of transport a transmission uses depends on the mapping structure of that transmission as it travels from end-to-end.

To filter by transport::
. Select the Transmissions View on the Central Pane
. Click on the Transport tab in the Filter Bar
. Select a Transport from the dropdown list

(Transports Include)::

* AS2
* SFTP
* FTPS
* HTTP
* RNIF
* PortX Hub
* Other

Only transmissions of that transport type appear in the Content Area.


==== Transport Problem Identification

If you notice that you are getting a large number of errors from a single type of transport, you can sort your transmissions using a filter (such as Relationship) in combination with the xref:transmissions-view.adoc[Transmissions View]. The filter allows you to view a given transport type and see the differences between those that failed and those that succeeded.

You can find additional relevant information in the xref:transmissions-view.adoc#transmissions-detail-pane[Transmissions Detail Pane] to the right. In the Detail Pane, you can see what happened with individual transactions with which transmissions were involved through a navigation button in the upper corner.

This allows you to follow transactions through their entire cycle, and if necessary replay them through the *Replay* button.

Because consistent navigation is helpful in looking for patterns and correcting errors, many filters persist from view to view. This allows you to look for commonalities across data types.

== When a Partner Needs Records

Often, a partner requires specific information relating to a transaction, transmission, or document. The following explains ways to access and use that information.

=== Findig a Transmission

. On the xref:central-pane-elements.adoc#view-dropdown-list[View Dropdown List] of the xref:transaction-monitoring.adoc[ Transaction Monitor Page], choose *Transmissions*.
+
The Transmissions View appears.
+
. In the *Transmission ID* filter, enter the partner ID.
+
The Transmissions Detail Pane populates with information that is likely relevant the partner's request.
+
. To copy a long string for partner use, click the blue *copy* icon to the right of the string.
+
Additional relevant information can be found using the various filter and sort possibilities this view presents.
+
NOTE: You can always use the *Reset Filters* button to get back to the full view.
+
If you need to find out more information about a transmission including where it exists in a Transaction, you can click on the *Transaction* button in the upper right corner to view the transmission in the Transaction View content area.

== Tracking Documents

=== Finding Documents

. In the xref:central-pane-elements.adoc#view-dropdown-list[View Dropdown List] of the Transaction Monitoring Page, choose *Documents*.
+
The Documents View appears.
. In the *Document ID* filter, enter the Document ID that the partner provided you.
+
The Document Detail Pane populates with information that is likely relevant to the partner's request.
+
To copy a long string for partner use, click the blue *copy* icon to the right of the string.

Filter

Additional relevant information can be found using the various filter and sort possibilities this view presents.
+
NOTE: You can always use the *Clear Filters* button to get back to the full view.
+
If you need to find out more information about a document, or to see where it fits into the bigger picture, you can click on the *Transaction* button in the upper right corner to view the document in context.
