== Tracking Transmissions 
Transaction Monitor allows you to track transmissions as they travel from end to end through Ihub.  

See also xref:central-pane-elements.adoc#transmissions-view[Transmissions View] for more information.

=== Track in the Dashboard
The xref:central-pane-elements.adoc#dashboard[Dashboard] at the top of the xref:transaction-monitoring.adoc[Transaction Monitoring Page] provides a data summary of what has happened in a given timeframe (the default setting is current day) including how many transmissions have been detected during that timeframe.

Start::
. Hover over different slices of the Transmissions Pie Chart to see what types of transmissions have occurred.
. To see information for a given transmission type, click one of the slices.
+
The Transmissions View appears, showing only the transmission type you selected in the Content Area.

=== Track in Transactions View
Tracking a transmission in Transactions View is a useful way to quickly find detailed information on a transmission, such as:

* Who it is From 
* The Transmission Type
* The Message Payload
* The Status
* The Transmission ID
* The Partnership ID

//-

Start::
. Click on the *Transactions* view from the View Dropdown List
+ 
The Transactions View Appears
. In the Timeframe Dropdown List, choose a timeframe that matches the timeframe of the transmission event.
+ 
Only transactions of that timeframe appear in the Content Area.
. Click on the transaction containing the transmission.
+
The Transaction Event Rows appear.
. Click on the Transmission Event from the Transaction Event Rows.
+ 
The Transmission Detail Pane appears.

==== Detail Pane
Use information in the Transmission Detail Pane to facilitate and manage the transmission.

Complete Message Payload::
. Click the blue arrow next to *Message Payload* in the Detail Pane
+
The complete Message Payload appears with the following options:

* Download
* Copy Content  
* Copy Payload URl
* Minimize
* Close

Transmission ID::
. In the Detail Pane, click the blue copy icon next to Transmission ID. 
. Save the Transmission ID to quickly access the Transmission in Transmissions View.

NOTE: You can always use the *Reset Filters* button to get back to the full view.

=== Track in Transmissions View
Tracking in xref:central-pane-elements.adoc#transmissions-view[Transmissions View] allows you to apply various filters such as:

* Relationship
* File Name
* Transport
* Transmission ID

Use these filters to compare transmissions and locate specific transmissions in Ihub.

Viewing Filter::
Apply the Viewing filter at any time to batch transmissions by Actor Type in the xref:central-pane-elements.adoc#content-area[Content Area]. You may select the following buttons in the xref:central-pane-elements#filter-bar[Filter Bar].
* Both
* Partners
* Applications

==== Track by Relationship (Your Company B2B)
Use the Relationship filter to track trasmissions between Actors (partners or applications). This filter is useful in that it allows you to assess multiple transmissions that occur between Your Company and specific Actors.

Start::
. Select the *Transmissions* in the xref:central-pane-elements#view-dropdown-list[View Dropdown List].
+
The Transmissions View appears.
. In the Timeframe Dropdown List, choose a timeframe that matches the timeframe of the transmission event.
+ 
Only transmissions of that timeframe appear in the Content Area.
. Click the *Relationship* tab in the Filter Bar.
. In the dropdown list select Your Company on the left and an Actor on the right.
+
Only transmissions of this relationship appear in the Content Area.

You can view transmissions of other actor relationships by setting new values in the Relationship Filter.

Relationship Filter Settings::

* Application -> Partner
* Partner -> Partner
* Application -> Application
* Your Company -> Application
* Your Company -> Partner

//-

* Click the *Transaction* button in the Transmission Detail Pane at the top right to view the transaction with which this transmission is associated. 

==== Track by Transport

Apply additional filters such as *Transport* to further track transmissions. A transport indicates the way in which a transmission is recieved and/or sent. The type of transport a transmission uses depends on the map that a transmission uses, as it travels from end-to-end in Ihub.

Start::

. Select *Transmissions* in the View Dropdown List.
+ 
The Transmissions View appears.
. Click on the *Transport* tab in the Filter Bar.
+
The Transport Dropdown List Appears.
. Select a *Transport* from the dropdown list.
+
Only transmissions of your selected transport type appear in the Content Area.

==== Transport Problem Identification

If you notice that you are getting a large number of errors from a single type of transport, you can sort your transmissions using a filter (such as Relationship) in the Transmissions View. The filter allows you to view a given transport type and see the differences between those that failed and those that succeeded.

You can find additional relevant information in the Transmissions Detail Pane to the right. In the Detail Pane, you can see what happened with individual transactions with which transmissions were involved through the *Transaction* navigation button in the upper corner.

This allows you to follow transactions through their entire cycle, and if necessary replay them through the *Replay* button.

==== Track by Transmission ID
Use the Trasmission ID Filter to quickly track a transmission.

. Select *Transmissions* in the View Dropdown List.
+
The Transmissions View appears.
+
. In the *Transmission ID* filter, enter the Transmission ID.
+
Only the transmission you enter appears in the Content Area.

The Transmissions Detail Pane populates with information that is likely relevant the partner's request.

To copy a long string for partner use::
. click the blue *copy* icon to the right of the string.
+
Additional relevant information can be found using the various filter and sort possibilities this view presents.

//-

* Click the *Transaction* button in the Transmission Detail Pane at the top right to view the transaction with which this transmission is associated. 

NOTE: You can always use the *Reset Filters* button to get back to the full view.