== Transactions View


The transactions view is the default view for the xref::transaction-monitoring.adoc[Transaction Monitor Page].

===  Content Area

In the content area, each row has 10 columns which present data about each transaction.

Column 1 (Replay Indicator):: This column presents a _grey circle_ icon:fa fa-circle-o[] at the top of the column allowing you to select all incomplete transactions in the content area below for replay. 
You can also select indivdual incomplete transactions in this column for replay.

Select incomplete transaction(s) and you may replay by clicking the blue [blue]#*Replay*# button in the top right of the <<Filter Bar>>.

Column 2 (Status Indicator):: 
This column contains the symbols icon:fa fa-check[role="green"]  or  icon:fa fa-exclamation-triangle[role="red"].
* A _green checkmark_ icon:fa fa-check[role="green"] means the transaction was successful
* A _red caution sign_ icon:fa fa-exclamation-triangle[role="red"] means that an error occurred somewhere in the transaction.

Column 3 (Replay Status Indicator)::
This column contains the symbols: icon:fa fa-clock-o[role="red"] icon:fa fa-repeat[role="blue"] icon:fa fa-undo[]
* An _orange clock_ icon:fa fa-clock-o[role="red"] means a replay is requested and currently being processed.
* A _blue partial circle with an arrowhead pointing right_ icon:fa fa-repeat[role="blue"] means that the transaction has been replayed.
* A _gray partial circle with an arrowhead pointing left_ icon:fa fa-undo[], means that the transaction is a replay of another transaction

Column 4 (Proceeding Transaction Type)::
This column contains symbols indicating the _preceding_ transaction type.
* 
* 
* 
* 
Column 5 (Next Transaction Type)::
This column contains symbols indicating the _next_ transaction type.
* 
* 
* 
* 

Column 6 (Status):: A detailed transaction status label

Column 7 (Name):: A detailed transaction label

Column 8 (From):: From whom the transaction originated

Column 9 (To):: To whom the transaction is destined

Column 10 (Date):: Date and time at which the transaction occurred

==== Transaction Event Rows

To view detailed information for the events that comprise a transaction, click anywhere in a transaction row. A new table appears beneath the transaction row. Events appear in inverse chronological order (oldest first). Columns are:

From:: Partner from whom the event originated
To:: Partner to whom the event was sent
Type:: Event type
Date:: Date and time at which the event occurred
Label:: Indicates what happened in the event

=== Transaction Detail Pane (Right)
Hidden when no transaction is selected and contains:

* Preceding transaction ID and Link
* Next transaction ID and Link
* From
* To
* Date
* Transaction ID icon:fa fa-plus-square-o[role="blue"] 

==== Action Icons
* The _copy_ icon icon:fa fa-plus-square-o[role="blue"] allows you to copy informaiton to your clipboard

==== Links
* Click [blue]#*View Preceding Transaction*# to see the preceding transaction
* Click [blue]#*View Next Transaction*# to see the next transaction

If a transaction has been replayed icon:fa fa-repeat[role="blue"] a [blue]#View replays# link appears. 

* Click the [blue]#View replays# link to view transaction replays

If a transaction is a replay of a transaction icon:fa fa-undo[] a [blue]#View original# link appears.

* Click the [blue]#View original# link to view the original transaction

** Additionally you can copy the Original Transaction ID by clicking the copy icon:fa fa-plus-square-o[role="blue"] action icon.


==== Filters

You can filter transactions based on:

Date of Transaction::
* Today
* Past 48 Hours
* 1 Week
* 1 Month

* Custom Range
** *From*: Select a date from the calendar; only transactions that occurred after that date will appear.
** *To*: Select a date from calendar; only transactions that occurred before that date will appear

View::
In the <<View Dropdown List>> filter by:
* Both
* Partners
* Applications

Relationship:: Filter by the application or partner between which the transaction occurs.
* Choose the Partner or Application from the dropdown menu

Transaction ID:: Filter by individual Transaction ID.
* You can view replays of this Transaction ID by clicking [blue]#View replays# in the <<Transaction Detail Pane (Right)>>.


==== To Show all Transactions
Click [blue]#*Reset filters*# at the top right of the Filters Bar.

