=== Transactions View


The Transactions View is the default view for the xref::transaction-monitoring.adoc[Transaction Monitor Page].

====  Content Area

In the content area, each row has 10 columns which present data about each transaction.

Column 1 (Replay Indicator):: This column presents a _grey circle_ at the top allowing you to select all incomplete transactions in the content area, following your set filter paramaters.
* Allows you to select all incomplete transactions.
* Allows you to select individual incomplete transactions.

Once selected, you may replay your incomplete transaction(s) by clicking the blue *Replay* button in the top right of the page.

Column 2 (Status Indicator):: 
Contains the symbols icon:fa fa-check[role="green"]  or  icon:fa fa-exclamation-triangle[role="red"].
* A _green checkmark_ icon:fa fa-check[role="green"] means the transaction was successful
* A _red_ icon:fa fa-exclamation-triangle[role="red"] means that an error occurred somewhere in the transaction.

Column 3 (Replay Status Indicator)::
This column contains symbols: icon:fa fa-clock-o[role="red"] icon:fa fa-repeat[role="blue"] icon:fa fa-undo[]
* An _orange clock_ icon:fa fa-clock-o[role="red"] meaning  a replay is requested and currently being replayed.
* A _blue partial circle with an arrowhead_ icon:fa fa-repeat[role="blue"]  which means that the transaction has been replayed.
* A gray partial circle with an arrowhead pointing left icon:fa fa-undo[], which means that the transaction is a replay of another transaction


////
Replay Status:: This column contains symbols :
* A blue partial circle with an arrowhead pointing right, which means that the transaction has been replayed
* A gray partial circle with an arrowhead pointing left, which means that the transaction is a replay of another transaction
* A gray circle with two sequential arrows, which means the transaction is currently being replayed
* An empty gray circle indicating the transaction can be replayed.
////
Column 4 (Proceeding Transaction):: This column contains symbols:
* 
Column 5 (Next Transaction)::

Column 4 (Status):: A detailed transaction status ide 

Column 3 (From):: The partner from whom the transaction originated

Column 4 (To):: To whom the transaction was destined

Column 5 (Date):: Date and time at which the transaction occurred

==== Transaction Event Rows

To view detailed information for the events that comprise a transaction, click anywhere in a transaction row. A new table appears beneath the transaction row. Events appear in inverse chronological order (oldest first). Columns are:

From:: Partner from whom the event originated
To:: Partner to whom the event was sent
Type:: Event type
Direction:: Either *Inbound* or *Outbound*
Date:: Date and time at which the event occurred
Label:: Indicates what happened in the event

==== Transaction Detail Pane
This pane appears on the right side of the page. In addition to information displayed in the <<Transaction row>>, it displays the *Transaction ID*.

If a transaction has been replayed, a *view replays* link appears, enabling you to view replays for the transaction.
icon:fa fa-clock-o[role=#FFA500]

==== Filters

You can filter transactions based on:

Date::
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range

Viewing::
In the <<View Dropdown List>> filter by:
* Both
* Partners
* Applications

From:: Select a date from calendar; only transactions that occurred after that date will appear.
To:: Select a date from calendar; only transactions that occurred before that date will appear.

Relationship:: The application or partner between which the transaction occurs. For more information, see xref:partner-configuration[Partner Configuration].
Transaction ID:: ID that you enter. When a Transaction ID filter is set, you can choose to include the replayed transactions originated from that Transaction ID.


==== To show all transactions
Click *Reset filters*.

==== Top Bar
* The *Replay* button will appear if the transaction you have selected can be replayed.
