== Transmissions View
:icons: font
The transmissions view presents data on each transmission between applications and partners in xref:transaction-monitoring[Transaction Monitor].

For more information on transmissions see xref:tracking-examples.adoc#tracking-transmissions[Tracking Examples]

=== Content
Each row has 5 columns:

. *From:* Who the transmission came from
. *To:* Who the transmission was sent to
. *Date:* Date and time at which the transmission occurred
. *Transmission Type:* The protocol the transmission was sent over
. *Label:* Any label associated with the transmission

=== Transmission Detail Pane (Right)
This pane is hidden when no transmission is selected. It contains:

* From 
* Transmission Type
* Date
* The Message payload icon:share[role="blue"] 
* Status
* Transmission IDs icon:plus-square-o[role="blue"]

==== Action Icons
* The blue copy icon icon:plus-square-o[role="blue"] allows you to copy information to your clipboard
* The blue share icon icon:share[role="blue"] opens a detail page that shows the complete message payload.
This detail page allows you to:
** Copy Payload URL
** Download 
** Copy content to clipboard

==== Buttons
* A *Transaction* icon:exchange[] button will appear when a transmission is selected
** This will take you to the xref:central-pane-elements#transactions-view[Transactions View] and highlight this specific transmission

=== Filters
You can filter transmissions based on:

Date::
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range
** *From*: Select a date from the calendar; only transmissions that occurred after that date will appear.
** *To*: Select a date from calendar; only transmissions that occurred before that date will appear
View::
* Both
* Partners
* Applications

Relationship:: Select the partner or application associated with the transmission
File Name:: Enter in part or all of a file name
Transport:: Select the transport protocol the transmission was sent over
Transmission ID:: Allows you to filter for a transmission by entering the ID

==== To Show all Transmissions
Click icon:trash-o[role="blue"] [blue]#*Reset Filters*# in the top right.

