= Central Pane Elements
:icons: font

== Dashboard
Located at the top of the xref:transaction-monitoring.adoc#Central-Pane[Central Pane], the Dashboard:

* Provides data for the timeframe you select in the <<Timeframe Dropdown List>>.
* Contains a icon:refresh[role="blue"] [blue]#*Refresh Data*# button in the upper left allowing you to refresh all page data.

== Timeframe Dropdown List

Located in the upper left of the xref:transaction-monitoring.adoc#Central-Pane[Central Pane], this enables you to present transaction data specific to the following timeframes:

* *Today* (Default)
* *Past 48 Hours*
* *1 Week*
* *1 Month*
* *Custom Range*


== Dashboard Data

Between the <<Dashboard>> and the <<View Dropdown List>>, dashboard data is presented in two forms:

Numerical form:: The actual number.

Pie chart::
* A representation of the data as a percentage of all data over the selected time frame.
* When you hover over or click on a section of the pie chart, the section illuminates and provides the number corresponding to that section.
* When you click a section of the piechart, the content area will apply necessary filters to display the corresponding data in the <<Content Area>>.
* Click *Overview* in the top left, to either raise or collapse your Dashboard Data on the screen

== View Dropdown List

This menu, above the <<Filter Bar>>, presents the following view options:

* <<Transactions View>>
* <<Transmissions View>>
* <<Errors View>>
* <<Documents View>>

The type of data that appears in the <<Content Area>> depends on the menu option you choose in the <<View Dropdown List>>.

== Filter Bar
Located below the <<View Dropdown List>>, this enables you to filter the results of a content view.

* Consists of Dropdown Filter lists that enable you to specify the criteria by which you want to filter.
* Which specific Dropdown Filter Lists appear depends on your selection in the <<View Dropdown List>>.
* Any of the type-able fields will auto-filter as you type into them. In some cases, copying and pasting the value may be helpful.
* Features a Viewing filter allowing you to choose:
** Both
** Partners
** Applications
* Includes a icon:trash-o[role="blue"] [blue]#Reset Filters# button in the top right.

=== To Reset a Filter

. Click the Dropdown Filter List you want to clear.
+
The Filter List appears.
. At the top right of the Filter List, click the [blue]#*Reset*# button.

=== To Reset all Filters

At the top right side of the Filter Bar, click icon:trash-o[role="blue"] [blue]#*Reset Filters*#


== Content Area

A table appears below the Central Pane. Table column headings depend on the choices you make in the <<Timeframe Dropdown List>> and the <<View Dropdown List>>.

The following Content Views are possible:

include::{partialsdir}/transactions-view.adoc[]

include::{partialsdir}/transmissions-view.adoc[]

include::{partialsdir}/errors-view.adoc[]

include::{partialsdir}/documents-view.adoc[]


