= Central Pane Elements

=== Dashboard

* Top of the Central Pane
* Provides data for the timeframe you select in the <<Timeframe Dropdown List>> at the upper left.

=== Timeframe Dropdown List

Enables you to present transaction data specific to the following timeframes:

* *Today*
* *Past 48 Hours*
* *This Week*
* *This Month*

The default setting is *Today*.


=== Dashboard Data

Between the <<Timeframe Dropdown List>> and the <<View Dropdown List>>, dashboard data is presented in two forms:

Numerical form:: The actual number.

Pie chart::
* A representation of transaction data as a percentage of all data of the selected type over the selected time frame. It is split into different sections of transaction data.
* When you hover over or click on a section of the error pie chart, the section illuminates and provides the number corresponding to that section.
* When you click a section of the piechart, the content area will apply necessary filters to display the corresponding data in the <<Content Area>>.
* Data types include _Transmissions_, _Transactions_, _Errors_, _Partners + Applications_.

==== Refresh Data

To the left of the <<Timeframe Dropdown List>> you can refresh the data on the page by clicking *Refresh Data*.

=== View Dropdown List

This menu, just above the <<Filter Bar>> grid, presents the following view options:

* *Transactions*
* *Transmissions*
* *Errors*
* *Documents*
* *Partner Conversations*

The type of data that appears in the <<Content Area>> depends on the menu option you choose in the _View Dropdown List_.

=== Filter Bar

* Enables you to filter the results of a view.
* Consists of Dropdown Filter lists that enable you to specify the criteria by which you want to filter.
* Which specific Dropdown Filter Lists appear depends on the value in the <<View Dropdown List>>.
* Any of the type-able fields will auto-filter as you type into them. In some cases, copying and pasting the value may be helpful.

==== To Clear a Filter

. Click the Dropdown Filter List you want to clear.
+
The Filter List appears.
. At the top right of the Filter List, click the *clear* button.

==== To Clear All Filters

. At the top right side of the Filter Bar, click  *Reset Filters* .


== Content Area

A table appears in the lower part of the Central Pane. Table column headings depend on  on the choices you make in the <<Overview for _timeframe_ Dropdown List>> and the <<View Dropdown List>>.

The following views are possible:

include::{partialsdir}/transactions-view.adoc[]

include::{partialsdir}/transmissions-view.adoc[]

include::{partialsdir}/errors-view.adoc[]

include::{partialsdir}/documents-view.adoc[]

include::{partialsdir}/partner-conversations-view.adoc[]


* xref:transactions-view.adoc[Transactions View]
* xref:transmissions-view.adoc[Transmissions View]
* xref:errors-view.adoc[Errors View]
* xref:documents-view.adoc[Documents View]
* xref:partner-conversations-view.adoc[Partner Conversations View]
