= Examples
:keywords: b2b, portal, partner, manager, environments

<<<<<<< HEAD:partner-manager/modules/ROOT/pages/examples.adoc
This page identifies examples of  xref:anypoint-partner-manager[PortX] in use.
=======
This page identifies examples of  xref:integration-hub[Integration Hub] in use.
>>>>>>> 0f39bfe... global change to integration hub:integration-hub/modules/ROOT/pages/examples.adoc

For conceptual information, see xref:key-concepts[Key Concepts].

For information about the procedures you would use to implement a given example, see xref:partner-configuration[Configure Trading Parners] and xref:transaction-monitoring[Transaction Monitoring].


== End-to-End Use Case

<<<<<<< HEAD:partner-manager/modules/ROOT/pages/examples.adoc
In this example, a user performs a series of configuration tasks in PortX and Anypoint Studio, resulting in the ability to view events and track transmissions.
=======
In this example, a user performs a series of configuration tasks in Integration Hub and an Enterprise Service Bus (ESB), resulting in the ability to view events and track transmissions.
>>>>>>> 0f39bfe... global change to integration hub:integration-hub/modules/ROOT/pages/examples.adoc

=== In Integration Hub

* Enter home organization settings
* Enter external trading partner settings

=== In ESB

. Create your flow.
. Configure the Integration Hub Connector.
. Configure Integration Hub-enabled connectors to use the Integration Hub Connector.
. Use standard connectors and processors to complete the processing and integration of the message into downstream systems as required.

=== Back in Integration Hub

<<<<<<< HEAD:partner-manager/modules/ROOT/pages/examples.adoc
Go to the B2B Transmissions area of PortX to view tracked events and messages.
=======
Go to the B2B Transmissions area of Integration Hub to view tracked events and messages.

// include::_sources/content-based-routing-example.adoc[]
>>>>>>> 0f39bfe... global change to integration hub:integration-hub/modules/ROOT/pages/examples.adoc


// Promotion Scenarios


include::{partialsdir}/promotion-scenarios.adoc[leveloffset=+1]

// removed image PromoteIDsOffCertsOn kris 7/1/2017


include::{partialsdir}/tracking-scenarios.adoc[leveloffset=+1]
