= Integration Hub
:keywords: b2b, introduction, portal, partner, manager

Integration Hub provides a single web-based user interface for <<Transaction Monitoring>> and <<Partner Configuration>>.

== Transaction Monitoring

Because B2B transactions often communicate contractual obligations between companies, it is desirable (and often necessary) to track all transmissions sent or received, storing the  transmission content as well as metadata (such as data and time the transmission was sent or received, the identity of the partner, and success or failure of processing). Integration Hub provides a simple, secure, and integrated mechanism for tracking B2B transactions. Uses for this data include:  

* Non-repudiation
* Correlation of acknowledgments
* Error correction
* Auditing

For more information, see xref:transaction-monitoring.adoc[Transaction Monitoring].

== Partner Configuration

Integration Hub provides the ability to edit, store, and retrieve configuration settings for the transport and format of B2B messages. For example, EDI messages are often sent over the AS2 protocol in order to ensure security and integrity of the transmissions. Each trading partner may have different AS2 settings; for example, each partner will have its own certificate. In addition, different partners may use different format protocols such as EDI X12, EDIFACT, or XML, and they may use different options within those protocols. Integration Hub allows this configuration data to be managed outside of your applications, so that they can be reviewed without looking at the code and updated without re-deploying your components.


