= One Document Type, Multiple Internal Routes

In this scenario, your organization receives a document from a Partner. IH has been configured to process the document in two ways:

* Map the document 


receive a document of this Document Type, IH routes the document to an internal API. If IH has not been configured to receive a document of this Document Type, IH rejects the document.

Relationships
There are two Relationships in this scenario:

== Goal

Here our users want to receive a single document Q from PartnerA, they then want to do two things to it. First they want to Pass it through to a backup that stores all documents they receive. Then they also want to map it once to the internal standard Document C and send it to a backend Database DATA.

== Setup

There are two relationships in this scenario:

[YourCompany B2B:Any]
Universal relationship between your company and any partner.
Artifacts used across all partners with whom you do business.
[PartnerA:YourCompany B2B]
Your relationship with the partner with whom you are doing business (in this case, PartnerA).
Contains artifacts used only with this partner.




== Artifacts in [YourCompany B2B:Any]
* Document C

** A document you use internally in your company.

* Endpoint DATA

** The endpoint that points to your internal database.

* Endpoint Backup

** The endpoint that points to your backup API that you back up all received documents to. 

* Target Channel DocC-to-Data

** This channel will take the internal document C and send it to Endpoint Data.

== [PartnerA:YourCompany B2B]
* Endpoint RecFromA

** This is the endpoint on which you expect to receive documents from PartnerA.

* Document Q

** A document you expect to receive from your partner.

* Map Q-to-C

** This map will convert the document Q into document C

* Source Channel DocQ-to-DocC

** This source channel will map the document Q into the document C

* Source Channel DocQ-Passthrough

** This source channel will pass the Document Q to whatever Target channel is selected.

* Target Channel DocQ-to-Backup

** This source channel will pass the Document Q to the Backup Endpoint

* Transaction DocQ-to-DocC-to-Data

** This transaction is the combination of the Source Channel DocQ-to-DocC and the Target Channel DocC-to-Data. And when combined it will be a transaction that receives a document Q maps it to document C and then sends it to the database DATA. This transaction has the From Partner set to PartA and the To Partner set to Your Company B2B.



== Execution

== ParnetA sends Document Q to Endpoint RecFromA.

* Integration Manager:

** Receives Document Q

** Attempts to resolve routes
** Finds 2 Transactions DocQ-to-DocC-to-DATA:(PartnerA), and DocQ-Passthrough:(PartnerA)
** Executes both transactions, 

*** One maps the Document Q to Document C and Sends Document C to Endpoint DATA.

*** One sends the Document Q to the Endpoint Backup.



