= Routing Scenarios

Pages in this section present scenarios that identify and illustrate:

* Integration Hub (IHub) xref:actors-relationships-and-artifacts.adoc[Actors, Relationships and Artifacts]
* How you can configure these IHub components to implement routing objectives.

== xref:basic-routing-scenario.adoc[Basic]
Your organization receives a document from a Partner. If IHub has been configured to receive a document of this Document Type, IHub routes the document to an internal API. If IHub has not been configured to receive a document of this Document Type, IHub rejects the document.

== xref:shared-routing-scenario.adoc[Shared ]
Your organization wants to receive a document Document from two Partners, map it to an internal standard, and send it to a backend database.

== xref:override-routing-scenario.adoc[Override]
In this scenario, your organization expects to receive documents of a single Document Type from multiple Partners.

If IHub has been configured to receive a document of this Document Type, IHub routes the document to an internal API.

However, one partner uses a variation of the Document Type, so you must override the standard Map that you use to transform that partner’s Document Type to your internal Document Type before routing.

If IHub has not been configured to receive a document of this Document Type, IHub rejects the document.

== xref:multi-route-routing-scenario.adoc[Multi-Route]
Your organization receives a document from a partner.
IHub has been configured to process the document in two ways:

* Route a copy of the document to an internal API
* Route a copy of the document directly to a destination you use to backup received documents. This routing is referred to as *passthru* because it does not require a map.  

== xref:multicast-routing-scenario.adoc[Multicast]
An Application sends a document to three other Applications. Two of the Applications require the document as-sent; the third requires the payload to be mapped.

== xref:application-sends-to-partner-routing-scenario.adoc[Application-Sends-to-Partner]
An Application sends a document to a Partner.

== xref:content-based-routing-routing-scenario.adoc[Content-Based-Routing] 
Your organization receives a Document from a Partner. If IHub has been configured to receive a document of this Document Type, IHub routes the document to an internal API. If IHub has not been configured to receive a document of this Document Type, IHub rejects the document.