= Seven Days to Integration Hub Mastery

Welcome to Integration Hub! We've created a week-long digital integration tour with Captain Cooper, an IHub expert. Meet Cooper and get started with with IHub concepts in https://ihub-concepts[this video].


Daily activities consist of:

* A _video_ in which an IHub expert reiterates scenario concepts and shows you the actual IHub screens that enable this example of the scenario to work.

* A _tutorial_ that provides step-by-step instructions for implementing this example of the scenario in your environment.

After Day One, each day also stops by a _walkthrough_ that illustrates the broader concepts of the scenario. 





https://drive.google.com/open?id=12AgIbzJsKVX4m_178H1dcf7b751Gs1pL[Get started with this video].

== Day One: Basic Routing 


We start with one of the most common scenarios in digital integration: Receiving, mapping, and sending a document from a partner to an internal endpoint. 



https://drive.google.com/open?id=12AgIbzJsKVX4m_178H1dcf7b751Gs1pL[This video tells the story of this scenario, YouTube-style].

xref:day-one-tutorial.adoc[This tutorial] provides step-by-step instructions for implementing this scenario in your organization. 

== Day Two: Basic Routing, EDI-style 

On Day Two, we take a look at an example of a basic routing scenario, your organization receives a xref:glossary#d[document] from a xref:glossary#p[Partner]. 
If IHub has been configured to receive a xref:glossary#d[document] of this xref:glossary#d[Document Type], IHub routes the xref:glossary#d[document] to an internal API. 
If IHub has not been configured to receive a xref:glossary#d[document] of this xref:glossary#d[Document Type], IHub rejects the document. 

* xref:basic-routing-scenario.adoc[Overview]
* Basic Routing Video

== Day Three: Shared Routing 

On Day Three, we In this example of a shared routing scenario, your organization wants to receive a document xref:glossary#d[Document] from two xref:glossary#p[Partners], map it to an internal standard, and send it to a backend database.

* Film video of Shared Routing Scenario (Cooper)
* xref:shared-routing-scenario.adoc[Shared Routing Scenario Walkthrough]

== Day Four: Override Routing

In this example of an override routing scenario, your organization expects to receive xref:glossary#d[document]s of a single xref:glossary#d[Document Type] from multiple xref:glossary#p[Partner]s.


If IHub has been configured to receive a document of this xref:glossary#d[Document Type], IHub routes the document to an internal API. 

However, one partner uses a variation of the Document Type, so you must override the standard xref:glossary#m[Map] that you use to transform that partner's Document Type to your internal Document Type before routing.

If IHub has not been configured to receive a document of this Document Type, IHub rejects the document. 

* Film video of Override Routing Scenario (Cooper)
* xref:override-routing-scenario.adoc[Override
Override Routing Scenario Walkthrough]

== Day Five: Multicast Routing

In this example of a multicast routing scenario, an xref:glossary#a[Application] sends a xref:glossary#d[Document] to three other Applications. Two of the Applications require the Document as-sent; the third requires the payload to be mapped.

* Film video of Multiroute or Multicast Routing Scenario (Cooper)
* xref:multicast-routing-scenario.adoc[Multicast Routing Scenario Walkthrough]

== Day Six: Chained Routing

In this example of a chained-transactions routing scenario, an xref:glossary#a[Application] sends a xref:glossary#d[Document] to a xref:glossary#p[Partner].

* Film video of Chained Routing Scenario (Cooper)
* xref:chained-transactions-routing-scenario.adoc[Chained Transactions Scenario Walkthrough]

== Day Seven: Advanced Topics

* xref:multi-route-routing-scenario.adoc[Multi-route]
* xref:content-based-routing-routing-scenario.adoc[Content-Based-Routing]



////
** xref:routing-scenarios.adoc[Routing Scenarios]
*** xref:basic-routing-scenario.adoc[Basic]
*** xref:shared-routing-scenario.adoc[Shared]
*** xref:override-routing-scenario.adoc[Override]
*** xref:multi-route-routing-scenario.adoc[Multi-route]
*** xref:multicast-routing-scenario.adoc[Multicast]
*** xref:chained-transactions-routing-scenario.adoc[Chained Transactions]
*** xref:content-based-routing-routing-scenario.adoc[Content-Based-Routing]
////