= PortX JD Edwards Connector for Mule 4
:keywords: add_keywords_separated_by_commas
:imagesdir: images
:toc: macro
:toclevels: 2

== Introduction

The PortX JDE Connector leverages the internal capabilities of Oracle’s JD Edwards EnterpriseOne™ solution, and uses the power of Oracle’s Java Dynamic Connector to provide interoperability with JD Edwards EnterpriseOne™ and external systems.


The PortX JDE Connector allows you to discover functions by name, providing you with full access to all Business Function signatures.

The PortX JDE Connector manages a cache repository for all functional metadata used at least once.

The results of a Function Call are injected into the flow as a Map containing key-value pairs with the invocation’s output values. This approach gives you the freedom of choice to construct complex flows and manage custom exception strategies.

=== Using the PortX JDE Connector

Use the connector to: ::

* xref:anypoint-studio-projet.adoc[Invoke a BSFN on JD Edwards Enterprise Server by passing it's paramaters].
* xref:anypoint-studio-project.adoc[Invoke a BSFN on JD Edwards Enterprise Server using Transaction Processing].
* Invoke a xref:demo_ube.adoc[UBE] by name.
* Check a xref:demo_ube_status.adoc[UBE Call Status asynchronously].
* Submit a UBE.
* Get UBE Job Status for a UBE using JDE Job Id.
* Get Outbound Events from a JD Edwards Application.
* Get EDI Event from EDI Application.
* xref:demo_poll_mbf_events.adoc[Poll MFB Events].
* xref:demo_poll_edi_events.adoc[Poll EDI Events].