== Documents View
:icons: font
<<<<<<< HEAD
The Documents View presents data on documents that are sent through xref:transaction-monitoring.adoc[Transaction Monitor].
=======
The Documents View presents data on documents that are sent through xref:transaction-monitoring.adoc[PortX Transaction Monitor].
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e
For more information on documents see xref:tracking-examples.adoc#tracking-documents[Tracking Documents].


=== Content
<<<<<<< HEAD
Each row has six columns:

From:: From whom the document was sent.

To:: To whom the document was sent.
=======
Each row contains six columns:

From:: Who the document was sent from.

To:: Who the document was sent to.
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e

Date:: Date and time at which the document was sent.

Standard:: The standard used to send the document.

<<<<<<< HEAD
Message Type:: The type of message that was sent.
=======
Message:: Type The type of message that was sent.
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e

Label:: Detail information describing the document.

=== Document Detail Pane (Right)
This pane is hidden when no document is selected. It contains:

<<<<<<< HEAD
Document ID:: Unique copyable document identification.
Document Definiton ID:: Unique copyable document definition identification. icon:plus-square-o[role="blue"]
Standard:: The document standard used.
Version:: The version of the document.
Message Type:: The type/reason for the message.
From:: From whom the document came.
To:: To whom the document is going.
Date:: Date the document was sent.
Duplicate Quiry:: Indicating if a document is a duplicate.
Message Payload:: icon:share[role="blue"] A link to the payload url and payload content
Partnership ID:: icon:plus-square-o[role="blue"] Unique copyable partnership identification.

==== *Detail Pane Action Icons*

* The *blue copy icon* icon:plus-square-o[role="blue"] enables you to copy information to your clipboard
* The *blue share icon* icon:share[role="blue"] opens a detail pane that shows the complete message payload.
=======
* Document ID icon:plus-square-o[role="blue"]
* Document Definiton ID icon:plus-square-o[role="blue"]
* Standard
* Version
* Message Type
* From
* To
* Date
* Duplicate Quiry
* Message Payload icon:share[role="blue"]
* Partnership ID icon:plus-square-o[role="blue"]

==== Action Icons

* The blue copy icon icon:plus-square-o[role="blue"] allows you to copy information to your clipboard
* The blue share icon icon:share[role="blue"] opens a detail pane that shows the complete message payload.
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e
This pane allows you to:
** Copy Payload URL
** Download 
** Copy content to clipboard

<<<<<<< HEAD
==== *Buttons*
* A *Transaction* icon:exchange[] button appears when a document is selected; which takes you to the xref:central-pane-elements#transactions-view[Transactions View] and highlights this specific document.
=======
==== Buttons
* A *Transaction* icon:exchange[] button will appear when a document is selected
** This will take you to the xref:central-pane-elements#transactions-view[Transactions View] and highlight this specific document
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e

=== Filters
You can filter documents based on:

Date::
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range
+
*From*: Select a date from the calendar; only documents that occurred after that date appear.
+
*To*: Select a date from calendar; only documents that occurred before that date appear.

View::
* Both
* Partners
* Applications

Relationship:: The partner or application that is associated with the document.
<<<<<<< HEAD
Message Type:: the message type found in the <<Document Detail Pane (Right)>>.
Property Name:: The document property name from the dropdown list.
Property Value:: The document property value found in the <<Document Detail Pane (Right)>>.
Standard:: The document standard protocol from the dropdown list.
Document ID:: The document ID found in the <<Document Detail Pane (Right)>>.
=======
Message Type:: The message type found in the <<Document Detail Pane (Right)>>.
Property Name:: The document property name from the dropdown list.
Property Value:: The document property value found in the <<Document Detail Pane (Right)>>.
Standard:: The document standard protocol from the dropdown list.
Document ID:: The document ID found in the <<Document Detail Pane (Right)>>
>>>>>>> 99ea637bc3c87a70f7efacb90df84012f1d06d6e

==== To Show all Documents
Click [blue]#*Reset filters*# in the top right.
