== Partner Conversations View

=== Content Area
Each content row has 5 columns.

Name:: The Document processing component.
Status:: The message status: _Pending_ or _Complete_.
Started:: The _Date_ and _Time_ at which the conversation started.
From:: The partner from whom the conversation come _from_.
To:: The partner from Whom the conversation went _to_.

===  Detail Pane
Within each partner conversation, a detail pane identifies the following data components:

* Document type
* Status
* Date
* From
* To

You can organize the results to list by first or last in each column. Click on the component collumn and then click the up or down arrow to the right.  

=== Filter

Using the <<Filter Bar>> You can filter partner conversations based on:

Date::
* Today
* Past 48 Hours
* This Week
* This Month
* Custom Range

Viewing:: 
* Both
* Partners
* Applications

Name:: Business Process Name

Status:: Complete or Pending

Relationship::
The application or partner between which the conversation occurs. 

* You can reset this filter in the <<Detail Pane>> by clicking *Reset* in the top right. 


==== To Show all Partner Conversations
Click *Reset Filters* in the top right of the <<Filter Bar>>.


