== Transactions View
The transactions view is the default view for the xref::transaction-monitoring.adoc[Transaction Monitor] page.
For more information on transactions see xref:tracking-examples.adoc#tracking-transactions[Tracking Examples].

=== Content
Each row has 10 columns:

Column 1 (Replay Indicator):: This column presents a grey circle icon:circle-o[] at the top of the column allowing you to select all incomplete transactions in the content area below. 
You can also select individual incomplete transactions in this column.

* Select incomplete transaction(s) and you may replay that transaction by clicking the blue [blue]#*Replay*# button in the top right of the filter Bar.

Column 2 (Status):: 
This column contains the following symbols:
* A green checkmark icon:check[role="green"] means the transaction was successful
* A red caution sign icon:exclamation-triangle[role="red"] means that an error occurred somewhere in the transaction.

Column 3 (Replay Status)::
This column contains the following symbols: icon:fa fa-clock-o[role="red"] icon:fa fa-repeat[role="blue"] icon:undo[]
* An orange clock icon:clock-o[role="red"] means a replay is requested and currently being processed.
* A blue partial circle with an arrowhead pointing right, icon:repeat[role="blue"] means that the transaction has been replayed.
* A gray partial circle with an arrowhead pointing left icon:undo[], means that the transaction is a replay of another transaction.

See xref:tracking-examples.adoc#Replaying-an-Incomplete-Transaction[Replaying an Incomplete Transaction] for information on replaying transactions.

Column 4 (Proceeding Transaction Type)::
This column contains symbols indicating the preceding transaction type.
* Batch
* Debatch
* Chain
* Multi-route

Column 5 (Next Transaction Type)::
This column contains symbols indicating the next transaction type.
* Batch
* Debatch
* Chain
* Multi-route

Hover over each icon for details on the Transaction type.

Column 6 (Status):: This column provides a detailed transaction status label.

Column 7 (Name):: This column provides the name of the transaction.

Column 8 (From):: This column indicates who the transaction originated from.

Column 9 (To):: This column indicates who the transaction is going to.

Column 10 (Date):: This column indicates the date and time at which the transaction occurred.

==== *Transaction Event Rows*

To view detailed information for the events that comprise a transaction, click anywhere in a transaction row. A new table appears beneath the transaction row. Events appear in inverse chronological order (oldest first). Details include:

From:: Partner or Application from whom the event originated
To:: Partner or Application to whom the event was sent
Type:: Event type
Date:: Date and time at which the event occurred
Label:: Type of event action in the transaction  

=== Transaction Detail Pane (Right)
Hidden when no transaction is selected, this pane includes:

* *Preceding transaction*: Preceding transaction type.
* *Next transaction*: Next transaction type.
* *From*: Who the transaction is from.
* *To*: Who the transaction is sent to.
* *Date*: The date of the transaction.
* *Transaction ID*: icon:plus-square-o[role="blue"] Unique copyable transaction identifier. 

=== Detail Pane Action Icons
* Click the blue *Copy* icon next to Transaction ID to copy it.

=== Detail Pane Links
* Click [blue]#*View Preceding Transaction*# to see the preceding transaction
* Click [blue]#*View Next Transaction*# to see the next transaction

If a transaction has been replayed icon:repeat[role="blue"] a blue [blue]#*View replays*# link appears.

* Click the [blue]#*View replays*# link to view transaction replays

If a transaction is a replay of a transaction icon:undo[] a blue [blue]#*View original*# link appears.

* Click the blue [blue]#*View original*# link to view the original transaction

See xref:tracking-examples.adoc#Replaying-an-Incomplete-Transaction[Replaying an Incomplete Transaction] for information on replaying transactions.

=== Filters

You can filter transactions based on:

Date of Transaction::
* Today
* Past 48 Hours
* 1 Week
* 1 Month
* Custom Range
** *From*: Select a date from the calendar; only transactions that occurred after that date will appear.
** *To*: Select a date from calendar; only transactions that occurred before that date will appear

View::
In the xref:central-pane-elements#View-Dropdown-List[View Dropdown List] filter by:

* Both
* Partners
* Applications

Relationship:: Filter by the application or partner between which the transaction occurs.
* Choose the Partner or Application from the dropdown menu.

Transaction ID:: Filter by individual Transaction ID.
* You can view replays of this Transaction ID by clicking [blue]#*View replays*# in the <<Transaction Detail Pane (Right)>>.


==== *Show all Transactions*
Click icon:trash-o[role="blue"] [blue]#*Reset Filters*# in the top right.

